### ISSUE TITLE
[bug] Does not work on Ubuntu 20.04 Focal Fossa + GS 3.36.2

### ISSUE THREAD

**Issue by Draky50110** [Ghostkeeper/gnome-wallpaper-changer#2]
Hello
Using Ubuntu Focal Fossa 20.04 with Gnome-Shell 3.36.2, it does not work.

![image](https://user-images.githubusercontent.com/1558487/83124365-69669f00-a0d6-11ea-8a7b-58c1f908cb60.png)

**Comment by keighrim** [comment]
@Draky50110 try reloading the shell (run --> `r`). That worked for me.
