### ISSUE TITLE
[feature request] please support a pallete cycling format

### ISSUE THREAD

**Issue by i30817** [Ghostkeeper/gnome-wallpaper-changer#7]
**Is your feature request related to a problem? Please describe.**
I'd love if the project could support this old technique of animation where the images don't actually change, just the color of pixels to support a animation. It's supposedely very lightweight and you can make effects that are timebased

Here is a example of what i mean: http://www.effectgames.com/demos/worlds/

click show options and move the time slider

**Describe the solution you'd like**
This technique is supposedly much more efficient that gifs or videos, which is the usual excuse for these never happening, so i though that this could be a nice alternative, even if with less images. I'm unsure if there is a actual format dedicated to this technique though.

**Describe alternatives you've considered**
Gifs obviously, but i kind of wonder, since it would require a dedicated thread from all that i understand of it. Maybe this would too, but since it's 'just' a palette switch, i think it might be more efficient than replacing the whole image.

**Additional context**
No context.

**Comment by Ghostkeeper** [comment]
You mean, to create/use a file format of animated images, where the pixel values don't change, but they refer to a palette where the colours of the palette change over time?

GIF indeed kind of allows that, but the rendering will have to re-render the whole image indeed.

Some other animated image file types are:
* APNG, which swaps out the whole pixel data every frame in the file format. And its older cousin MNG.
* WebP, not a palette-based format.
* All the "real" movie formats like HEVC, VP9, etc are also not palette-based.
* Aseprite, which is similar to GIF but doesn't support per-frame palettes.

The way that it works with GIF is that GIF can define a (local) palette per frame, and then have an identical frame of pixel data. So the identical frame there probably compresses fairly well even with GIF's limited RLE, but still requires re-interpreting and re-rendering of all of it.

So the way I see it, you'd either do this with GIF (which should already work in Gnome), or you'd create a whole new file format that allows this.

I think creating a whole new file format is out of scope for this plug-in. And frankly, creating a new algorithm for how images are rendered in your desktop background also. This extension merely swaps out the image link in the `org.gnome.desktop.background` Gnome preference at the moment. Any rendering algorithm I'd make with GJS would probably be less efficient than just using a GIF. Sorry!

**Comment by i30817** [comment]
> So the way I see it, you'd either do this with GIF (which should already work in Gnome), or you'd create a whole new file format that allows this.

So, i tried this extension with gifs now, and the image stays static. Did you mean i was supposed to install anything else to be able to use gifs, or is this a bug?

Second, i tried to switch around the option to 'scale to monitor' and nothing seems to be happening, either in the current image or the 'next' if i force the next image. Moreover, the image appears to be scaled to the whole screen... including the space currently occupied by the topbar in gnome (not ubuntu unity).

I updated to gnome 42.2 so maybe the problem with both of these is that though.
