### ISSUE TITLE
[bug] Only work in Light mode in GNOME 42.1

### ISSUE THREAD

**Issue by shtrom** [Ghostkeeper/gnome-wallpaper-changer#8]
**Describe the bug**
With GNOME 42.1 the dark-mode wallpaper is not changed. It is only set properly for the light mode. The dark-mode wallpaper remains unchanged.

![image](https://user-images.githubusercontent.com/160280/170851132-28e9c68b-a0b7-467a-917f-ce525873a9ce.png)

**Expected behavior**
The same image is set for both light and dark modes.

**Comment by SylChamber** [comment]
The Variety wallpaper app has the exact same problem. They fixed it: [Dark mode Ubuntu 22.04](https://github.com/varietywalls/variety/issues/495)

I applied the [fix mentionned in a comment](https://github.com/varietywalls/variety/issues/495#issuecomment-1077148274) manually on the Variety file specified, and it fixed the problem.

I bet the same fix would also work on gnome-wallpaper-changer.

**Comment by Ghostkeeper** [comment]
Thanks @SylChamber, that helps a lot!

I've made a fix using that information. Would you like to try installing this version to see if it works for you?
[wallpaper-changer@ghostkeeper.github.com.zip](https://github.com/Ghostkeeper/gnome-wallpaper-changer/files/10141630/wallpaper-changer%40ghostkeeper.github.com.zip)
(Or of course to manually make the changes I made in [that commit](https://github.com/Ghostkeeper/gnome-wallpaper-changer/commit/dbbcf41578c8648180f22e8f08eaaa6d130fb300), like you did with Variety.)

**Comment by mnwstl** [comment]
Hello! 

It worked for me with ubuntu 22.04.1 LTS - GNOME 42.5. 
I have the same problem with other applications. I'm going to study the case better.
I leave here the suggestion that the time could be also in seconds.

Thank you!
